In [34]:
import numpy as np

In [35]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [36]:
def generate_remaining_IDs(all_indices,removable_indeces):
    """
    usually :  all_indices = range(0,...)
    """
    new_indeces = []
    for i in all_indices:
        if i not in removable_indeces:
            new_indeces.append(i)

    return new_indeces

In [46]:
def reduce_adjacency_mat(old_mat,new_indices):#all_indices,remove_indices):
    # new_indices = generate_remaining_IDs(all_indices,remove_indices)
    print('initial dimention :',np.shape(old_mat))
    new_mat = np.zeros((len(new_indices),len(new_indices)))

    for x,i in enumerate(new_indices):
        for y,j in enumerate(new_indices):
            new_mat[x,y] = old_mat[i,j]

    print('final dimention :',np.shape(new_mat))
    return new_mat

In [40]:
def reduce_feature_mat(old_feature_mat,new_indices):#all_indices,remove_indices):
    print('initial dimention :',np.shape(old_feature_mat))
    # new_indices = generate_remaining_IDs(all_indices,remove_indices)
    mat = old_feature_mat.tolist().copy()

    modified_list = [mat[i] for i in new_indices]


    print('final dimention :',np.shape(modified_list))
    return np.array(modified_list)

In [41]:
import pandas as pd

def reduce_df(df,remove_indices):
    print('initial dimention :',df.shape[0])
    # Rows to remove (indices)
    rows_to_remove = [df.index[i] for i in remove_indices]

    # Remove the specified rows
    modified_df = df.drop(rows_to_remove)

    print('initial dimention :',modified_df.shape[0])
    return modified_df

---
### TEST

In [ ]:
adj_mat = np.random.randint(0,7,(5,5))
feature_mat = np.random.randint(0,7,(5,10))
fund_df = pd.DataFrame(np.random.randint(0,7,(5,3)))
fund_df.index = list('abcde')

all_indices = np.arange(5)
remove_indices = [1,3]

In [ ]:
adj_mat

array([[5, 1, 4, 2, 5],
       [5, 5, 0, 2, 0],
       [4, 5, 5, 0, 1],
       [3, 2, 0, 3, 6],
       [3, 2, 4, 4, 5]])

In [ ]:
feature_mat

array([[5, 5, 6, 1, 2, 1, 4, 5, 1, 6],
       [6, 6, 0, 6, 3, 5, 0, 6, 2, 6],
       [3, 1, 4, 5, 5, 6, 1, 3, 2, 1],
       [5, 4, 5, 6, 6, 2, 2, 5, 6, 5],
       [6, 6, 5, 5, 4, 1, 0, 5, 1, 5]])

In [ ]:
fund_df

0  1  2
a  4  2  1
b  3  3  3
c  6  4  1
d  4  3  0
e  4  2  3

In [ ]:
generate_remaining_IDs(all_indices,remove_indices)

[0, 2, 4]

In [ ]:
reduce_adjacency_mat(adj_mat,all_indices,remove_indices)

initial dimention : (5, 5)
final dimention : (3, 3)


array([[5., 4., 5.],
       [4., 5., 1.],
       [3., 4., 5.]])

In [ ]:
reduce_feature_mat(feature_mat,all_indices,remove_indices)

initial dimention : (5, 10)
final dimention : (3, 10)


array([[5, 5, 6, 1, 2, 1, 4, 5, 1, 6],
       [3, 1, 4, 5, 5, 6, 1, 3, 2, 1],
       [6, 6, 5, 5, 4, 1, 0, 5, 1, 5]])

In [ ]:
reduce_df(fund_df,remove_indices)

initial dimention : 5
initial dimention : 3


0  1  2
a  6  4  5
c  2  1  5
e  1  3  6

---
### Usage

In [42]:
new = np.load('/content/drive/My Drive/Data/ProcessedData/World/Names/5400_names_id.npy')
old_length = new.shape[0]
print(old_length)

5418


In [ ]:
countries = np.load('/content/drive/My Drive/Data/ProcessedData/World/Names/5400_country_id.npy')

In [ ]:
countries.shape

(5418,)

In [ ]:
countries

array([0, 3, 0, ..., 0, 7, 0])

In [ ]:
IDs,counts = np.unique(countries,return_counts=True)

In [ ]:
IDs,counts

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62]),
 array([2524,  311,  302,  263,  178,  170,  138,  105,  100,   94,   79,
          76,   65,   62,   59,   53,   52,   51,   46,   45,   40,   40,
          40,   39,   36,   35,   34,   33,   30,   27,   27,   26,   23,
          22,   22,   19,   17,   16,   15,   15,   13,   13,   10,    9,
           6,    5,    4,    4,    3,    3,    2,    2,    2,    2,    2,
           2,    1,    1,    1,    1,    1,    1,    1]))

In [ ]:
USA_countries = np.where(countries == 0)

In [ ]:
USA_countries[0]

array([   0,    2,    5, ..., 5414, 5415, 5417])

In [ ]:
np.random.shuffle(USA_countries[0])

In [ ]:
USA_countries[0]

array([ 829, 3512,  724, ..., 4831, 1953, 2599])

In [ ]:
remove_shares = USA_countries[0][:2124]
remove_shares.shape

(2124,)

In [ ]:
all_indices = np.arange(countries.shape[0])
new_indeces = generate_remaining_IDs(all_indices,remove_shares)

### Load Data

In [43]:
# feature_mat = np.load('/content/drive/My Drive/Data/ProcessedData/World/features/final feature mat/reduced_feature_mat5.npy')
adj_mat = np.load('/content/drive/My Drive/Data/ProcessedData/World/distance matrix/DTW_5400.npy')

ids = np.load('/content/drive/My Drive/Data/ProcessedData/World/Names/3300_names_id.npy')

In [44]:
adj_mat.shape

(5418, 5418)

In [ ]:
# feature_text = np.load('/content/drive/My Drive/Data/ProcessedData/World/features/xlnet_pca.npy')
# feature_text.shape

(3294, 200)

In [ ]:
# reduced_feature_mat = np.concatenate((feature_mat,feature_text),axis=1)
# reduced_feature_mat.shape

(3294, 484)

In [47]:
# reduced_feature_mat = reduce_feature_mat(feature_mat,ids)
reduced_adj_mat = reduce_adjacency_mat(adj_mat,ids)

initial dimention : (5418, 5418)
final dimention : (3294, 3294)


In [49]:
np.save('/content/drive/My Drive/Data/ProcessedData/World/distance matrix/DTW_3300',reduced_adj_mat)
# np.save('/content/drive/My Drive/Data/ProcessedData/World/adjacency matrix/5400/reduced_graph_a=1.5_b=0.5_sp=0.044',reduced_adj_mat)
# np.save('/content/drive/My Drive/Data/ProcessedData/World/Names/3300_names_id',new_indeces)